server:
  port: 8081
spring:
  application:
    name: jxpub-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jx_pub?characterEncoding=utf-8&useSSL=false
    username: root
    password: '021033'
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

pagehelper:
  helper-dialect: mysql

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jx.pub.manage.mapper : DEBUG

cookieDomain: localhost
picUrl: http://23wz.top:8888/


